---
name: Testing

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  test-reporting:
    runs-on: ubuntu-latest

    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev

      - name: Run tests
        run: |
          poetry run python test.py
